"""fixed FK names in tables

Revision ID: fa8c41a6a295
Revises: a5f5ac8ee83f
Create Date: 2025-06-29 12:50:06.930843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8c41a6a295'
down_revision = 'a5f5ac8ee83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('board')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint('cards_board_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'boards', ['board_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cards_board_id_fkey', 'board', ['board_id'], ['id'])

    op.create_table('board',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='board_pkey')
    )
    op.drop_table('boards')
    # ### end Alembic commands ###
